### PR TITLE
Exercise1

### PR DESCRIPTION
**Pull request by lance-go**
## Ticket
- [Ticket](https://www.notion.so/Exercise-1-f015d8c3af59421594b7fb007985e298?pvs=4)

## Task
- [x] Draw a square with input size

## Screenshot

ex1

### CODE REVIEW

**Review by drake-ho-goldenowl — APPROVED** [review]
LGTM

**Comment by lance-go** [comment]
> LGTM

what is LGTM?

**Comment by drake-ho-goldenowl** [comment]
> > LGTM
> 
> what is LGTM?

LGTM is "looks good to me" 👍

**Comment by lance-go** [comment]
> > > LGTM
> > 
> > 
> > what is LGTM?
> 
> LGTM is "looks good to me" 👍

oh well 👯

**Pull request merged**
